import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { unstable_setRequestLocale } from "next-intl/server"
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] })

type Props = {
  children: React.ReactNode;
  params: { locale: string };
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  params: { locale }
}: Props) {
  // Enable static rendering
  unstable_setRequestLocale(locale);
  return (
    <html lang={locale} suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster
            toastOptions={{
              unstyled: true,
              classNames: {
                toast: 'bg-background w-full md:min-w-64 py-4 flex items-center rounded-md shadow-md px-3 gap-1',
                title: 'text-red-400 text-sm',
                description: 'text-red-400',
                actionButton: 'bg-zinc-400',
                cancelButton: 'bg-orange-400',
                closeButton: 'bg-lime-400',

                error: 'bg-destructive',
                success: 'bg-green-500',
                warning: 'text-yellow-400',
                info: 'bg-blue-400',
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  )
}
